# -*- coding: utf-8 -*-
"""Admission_9676.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qxAUDn2ameupmcH9rlpQffbsTMpwUZZE
"""

gpa = float(input("Enter your GPA: "))
sat = int(input("Enter your SAT: "))

if gpa >= 3.75 and sat > 80:
  print("\nyou are admitted with scholorship!")
elif gpa >= 3.25 and sat > 70:
  print("\nyou are admitted!")
elif gpa >= 3.0:
  print("\nyou are on the waiting list!")
else:
  print("\nwe regret to inform you that we are unable to accept you to our program.")