# -*- coding: utf-8 -*-
"""Ass4_9676.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dRVs8zLG4wPpdgcHV5b4IEUCTMQv3G7W
"""

def function1():

  cities = ["Chicago", "NYC", "Houston", "Los Angeles", "San Francisco"]
  city = input("Which city would you like the hotel to be in? ")
  while city not in cities:
    print('Invalid city')
    city = input("Which city would you like the hotel to be in? ")

  startDate = input("Enter a start date MM/DD ")
  endDate = input("Enter an end date MM/DD ")
  while startDate >= endDate:
    print("End date must be after start date ")
    endDate = input("Enter an end date MM/DD ")

  return city, startDate, endDate

print(function1())

def function2():

  guests = int(input("How many guests? "))
  rooms = int(input("How many rooms? "))
  while guests > rooms * 4:
    print("One room allows up to 4 guests only ")
    guests = int(input("How many guests? "))
    rooms = int(input("How many rooms? "))


  roomTypes = ["Single King Bed", "Double Queen Bed", "Suite"]
  roomType = input("What kind of room? (Single King Bed, Double Queen Bed, Suite) ")
  while roomType not in roomTypes:
    print("Invalid room type")
    roomType = input("What kind of room? (Single King Bed, Double Queen Bed, Suite) ")

    return guests, rooms, roomType

print(function2())

def main():

  hotelName = "Hilton Hotel"
  customerName = input("Enter your name: ")

  city, startDate, endDate = function1()
  guests, rooms, roomType = function2()

  print(f"{customerName} booked {rooms} {roomType} rooms in {hotelName} {city} from {startDate} to {endDate}.")

