# -*- coding: utf-8 -*-
"""Ass5_9676.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lcj38TBgOEHbOvaMCIm3eOyPtehUwhH9
"""

def readPoem():
    try:
        with open("poem.txt", "r") as file:
            for line in file:
                print(line.strip())
    except FileNotFoundError:
        print("File not found.")


def countLinesNotStartingWithT():
    try:
        count = 0
        with open("story.txt", "r") as file:
            for line in file:
                if not line.startswith("T"):
                    count += 1
        print("Number of lines not starting with 'T':", count)
    except FileNotFoundError:
        print("File not found.")


def countTotalWords():
    try:
        with open("story.txt", "r") as file:
            content = file.read()
            words = content.split()
            print("Total number of words:", len(words))
    except FileNotFoundError:
        print("File not found.")


def findOccuranceOfThe():
    try:
        with open("notes.txt", "r") as file:
            content = file.read().lower()
            words = content.split()
            count = words.count("the")
            print("Occurrence of 'the':", count)
    except FileNotFoundError:
        print("File not found.")


def displayWords():
    try:
        with open("story.txt", "r") as file:
            for line in file:
                words = line.split()
                for word in words:
                    if len(word) < 4:
                        print(word)
    except FileNotFoundError:
        print("File not found.")