# -*- coding: utf-8 -*-
"""MidTerm_3304_9676.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ItzJJTXbBglZErdQfSRSu4k5jMkU1D8Z

MidTermQuestion01_9676
"""

# QUESTION 1

weekday = int(input("What is weekday of today? (1 - 7) "))
time = int(input("What is the time now? (0 - 23) "))
parrotTalking = input("Is parrot talking? (True or False) ")

if 1 <= weekday <= 5:
  if 9 <= time <= 20 and parrotTalking == "True":
    print("Parrot is having fun! ")
  elif 9 <= time <= 20 and parrotTalking == "False":
    print("Parrot is boring on weekday! ")
  elif 0 <= time <= 8 or 21 <= time <= 24 and parrotTalking == "True":
    print("Parrot is having trouble! ")
  elif 0 <= time <= 8 or 21 <= time <= 24 and parrotTalking == "False":
    print("Parrot is sleeping! ")
else:
  if 11 <= time <= 22 and parrotTalking == "True":
    print("Parrot is enjoying Weekend! ")
  elif 11 <= time <= 22 and parrotTalking == "False":
    print("Parrot is boring on Weekend! ")
  elif 0 <= time <= 10 or 23 <= time <= 24 and parrotTalking == "True":
    print("Parrot is having trouble! ")
  elif 0 <= time <= 10 or 23 <= time <= 24 and parrotTalking == "False":
    print("Parrot is sleeping! ")

"""MidTermQuestion02_9676"""

# QUESTION 2

itemPrice = 0.0
priceList = []
fullPriceCt = 0
finalDiscountCt = 0

while itemPrice != -1:
  itemPrice = float(input("What is the price of item? (Type -1 to end)"))
  if itemPrice != -1:
    priceList.append(itemPrice)


priceList.sort()

print("Total number of item prices: ", len(priceList))
print("The min item price is ", priceList[0])
print("The max item price is ", priceList[-1])
print("The medium item price is ", priceList[len(priceList) // 2])
print("The average item price is ", sum(priceList) / len(priceList))

for i in range(len(priceList)):
  if str(priceList[i]).endswith(".99"):
    fullPriceCt += 1
  elif str(priceList[i]).endswith(".17"):
    finalDiscountCt += 1

print("Number of item ends with .99 full price is ", fullPriceCt)
print("Number of item ends with .17 final discount is ", finalDiscountCt)

"""MidTermQuestion03_9676"""

# QUESTION 03

def sum67(numbers):
  total = 0
  insideFlag = False
  for number in numbers:
    if number == 6:
      insideFlag = True
    elif number == 7:
      insideFlag = False
    elif insideFlag == True:
      total += number
  return total


print(sum67([1, 1, 6, 7, 2]))
print(sum67([1, 2, 2]))
print(sum67([1, 1, 6, 3, 7, 6, 3, 7, 2]))
print(sum67([1, 1, 6, 3, 7, 4, 7, 2]))
print(sum67([1, 2, 2, 6, 99, 99, 7]))
print(sum67([1, 1, 6, 1, 7, 2, 6, 3, 7, 4]))

"""MidTermQuestion04_9676"""

# QUESTION 04

def canBalance(intArray):
  if len(intArray) == 1:
    return False

  for i in range(0, len(intArray)):
    leftList = intArray[:i]
    leftListOdd = []
    for number in leftList:
      if number % 2 != 0:
        leftListOdd.append(number)
    rightList = intArray[i:]
    rightListEven = []
    for number in rightList:
      if number % 2 == 0:
        rightListEven.append(number)
    if sum(leftListOdd) == sum(rightListEven):
      return True
  return False



print(canBalance([1, 1, 1, 2, 1, 1, 1]))
print(canBalance([2, 1, 5, 1, 1, 2, 3, 5]))
print(canBalance([2, 1, 5, 2, 3, 5]))
print(canBalance([10, 10]))