# -*- coding: utf-8 -*-
"""ClassEx01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iF_XeEQdonuww8Y5Wv0i8gSh-jacsEJS

Title: This is my very first Google colab exercise
"""

temperature =  int(input('What is the outside temperature?'))

if temperature < 50:
  print('Wear a coat!')
  print('end if statement')
elif temperature > 90:
  print('Bring a bottle of water!')
else:
  print('Nice weather!')
print('Here a new statement will be executed, not controlled by if')

"""Take a 0-100 score, generate a letter grade"""

score = int(input('What is your score?'))

if score >= 90:
  print('A')
elif score >= 80:
  print('B')
elif score >= 70:
  print('C')
elif score >= 60:
  print('D')
else:
  print('F')

"""Nested control-flow structure to compare two variables"""

salary = 60000
years_on_job = 3

if salary >= 30000:
  if years_on_job >= 2:
    print('Congratulations! Your mortgage has been approved!')
  else:
    print('Years on job must be larger or equal than 2 years')
else:
  print('The reason your salary is less than 30,000, you are rejected')

if salary >= 30000 and years_on_job >= 2:
  print('Congratulations! Your mortgage has been approved!')
else:
  print('Your mortgage application is rejected')

