# -*- coding: utf-8 -*-
"""ClassEx04_9676.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nlmoPtTZezB37OC-PG0N5OhMhKhjIV0L
"""

# Global variable
PI = 3.1415

# Void function
def welcome(name, gender):
    if gender == 'M':
        print('Welcome Mr. ', name)
    else:
        print('Welcome Ms. ', name)
    print('Global PI:', PI)
    print()

def main():
    global PI
    PI = 2.88  # Change the global PI value
    guest_list = ['James Bond', 'Jane Bond', 'Alice Bond']
    gender_list = ['M', 'F', 'F']

    for guest, gender in zip(guest_list, gender_list):
        welcome(guest, gender)  # Corrected the argument order

    print('PI is:', PI)

    # Calling the gross_salary function
    salary, tax = gross_salary(10, 5.5)
    print('gross_salary:', salary, 'tax:', tax)

main()

import random as r
import math as m

def main():
  for i in range(10):
    print(r.randint(50,100))
    print(r.random)

main()

