# -*- coding: utf-8 -*-
"""ClassEx03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T3ElKsKrBl81xFtvm6Bs209-2MrHBmzK
"""

#list practice
num_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
name_list = ['Alice', 'Bob', 'Charlie', 'David', 'Edward']

mix_list = num_list + name_list
print(mix_list)
print(num_list*3)

#index of a number
#find index of 'Charlie'
print(mix_list.index('Charlie'))

for name in name_list:
    print(name, 'index', name_list.index(name))

#print out all names except the first and last ones
print(name_list[1 : 4])
#print out all numbers in the first half of the list
half_index = len(num_list) // 2
print(num_list[: half_index])
print(num_list[half_index :])
print(num_list[::])
#print out all even number
print(num_list[: : 2])
print(num_list[: : 3])
#print out all odd number
print(num_list[1 : : 2])
name_list[2] = 'James Bond'
name_list.append('Elvis Alam')
name_list.extend(['Oscar', 'Fred'])
name_list.insert(2, 'AAA')

name_list.sort()
name_list.reverse()

name_list.remove('Elvis Alam')
del name_list[-1]
print(max(name_list), min(name_list))
print(name_list)

new_name_list = name_list
name_list.remove('Alice')
print(new_name_list)
print(name_list)