# -*- coding: utf-8 -*-
"""ClassEx05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16O6mXwNxbXZDtSWm6hkvUL0BhuqUDsR9
"""

#we will open/read the file (numbers.text test.txt)
#open function has three modules, r = read only, w = write only, a = appending
# https://drive.google.com/drive/folders/17UqjhioUKGkITUl_hjo9R3EaYv2t8Ri0?usp=drive_link
# from google.colab import drive; drive.mount('/content.drive')

try:
  filename= '/content/numbers.txt'
  file = open(filename, 'r')
  print(file)

  for line in file:
    print(int(line[:-1]) + 5)

  file.close()
except FileNotFoundError:
  print('Warning, your file', filename, ' is not found')

#open and write a file
try:
  filename = '/content/numbers.txt'
  file = open(filename, 'a')
  file.write('11\n22\n33\n')
  file.close()
except FileNotFoundError:
  print('Warning, your file', filename, ' is not found')
except FileExistsError:
  print('Warning, your file', filename, ' exists already')
finally:
  print('A surprise happened!')

try:
  filename = '/content/test.txt'
  newfilename = '/content/test_new.txt'
  file = open(filename, 'r')
  file_new = open(newfilename, 'w')
  line_ct = 1

  for line in file:
    file_new.writelines(line[:-1] + ' ' + str(line_ct) + '\n')
    line_ct += 1

  file.close()
  file_new.close()
except FileNotFoundError:
  print('Warning, your file', filename, ' is not found')