# -*- coding: utf-8 -*-
"""ClassEx02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a1d-Q43smei8FaXiRRseV2U3yXhzBoAB
"""

x = 1
print(x)
# equal sign means assigning reight hand side value to left hand side variable
x = x + 1
print(x)
x = x + 1
print(x)
x = x + 1
print(x)
x = x + 1
print(x)

# write a while loop to repeat this statement
# reset x value to 1
x = 1
upper_limit = int(input('How many numbers do you want'))
while x <= upper_limit:
    print(x)
    x = x + 2
# end of while loop
print('end of while loop')

#for loop section
for var in range(10, 0, -1):
    print(var)

for guest in ['Bob', 'Jane', 'Tim']:
  print(guest)

#nested while loop to mimic a clock running
hour = 0
min = 0
sec = 0
while hour <= 23:
  min = 0
  while min <= 59:
    sec = 0
    while sec <= 59:
      print(hour, ':', min, ':', sec)
      sec += 1
    #end of sec loop
    min += 1
  #end of min loop
  hour += 1
#end of hour loop